// <auto-generated />
namespace Project30.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updates));
        
        string IMigrationMetadata.Id
        {
            get { return "201301280203513_updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
